apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../../base/flaskapp

patches:
  - target:
      kind: Deployment
      name: flaskapp-depl
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
  - patch: |-
      apiVersion: v1
      kind: LimitRange
      metadata:
        name: flaskapp-limits
      spec:
        limits:
        - default: 
            cpu: 500m
            memory: 512Mi
          defaultRequest:
            cpu: 250m
            memory: 256Mi
          max:
            cpu: "1"
            memory: 1Gi
