apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  serviceName: "db-service"
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: mysql
          image: shehabfahmy/fawry-k8s-project-mysql:latest
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-cm
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: db-pvc

