apiVersion: v1
kind: LimitRange
metadata:
  name: flaskapp-limits
spec:
  limits:
  - default: 
      cpu: 250m
      memory: 256Mi
    defaultRequest:
      cpu: 125m
      memory: 128Mi
    max:
      cpu: 500m
      memory: 512Mi
    min:
      cpu: 100m
      memory: 100Mi
    type: Container
